# users = User.create!([
#   { name: "John Doe", password_digest: "kdsjafhiuvnu", email: "jdoe@gmail.com" },
#   { name: "Jane Smith", password_digest: "eiwuyrtioqewpni", email: "jsmith@gmail.com" },
#   { name: "IM Nuts", password_digest: "easkdjfhi", email: "imnuts@gmail.com" },
# ])

teams = Team.create!([

  ###  NFL
  { name: "Dallas Cowboys", league: "NFL", api_id: "DAL", api_used: "sportsfeed" },
  { name: "Arizona Cardinals", league: "NFL", api_id: "ARI", api_used: "sportsfeed" },
  { name: "Atlanta Falcons", league: "NFL", api_id: "ATL", api_used: "sportsfeed" },
  { name: "Baltimore Ravens", league: "NFL", api_id: "BAL", api_used: "sportsfeed" },
  { name: "Buffalo Bills", league: "NFL", api_id: "BUF", api_used: "sportsfeed" },
  { name: "Carolina Panthers", league: "NFL", api_id: "CAR", api_used: "sportsfeed" },
  { name: "Chicago Bears", league: "NFL", api_id: "CHI", api_used: "sportsfeed" },
  { name: "Cincinnati Bengals", league: "NFL", api_id: "CIN", api_used: "sportsfeed" },
  { name: "Cleveland Browns", league: "NFL", api_id: "CLE", api_used: "sportsfeed" },
  { name: "Denver Broncos", league: "NFL", api_id: "DEN", api_used: "sportsfeed" },
  { name: "Detroit Lions", league: "NFL", api_id: "DET", api_used: "sportsfeed" },
  { name: "Green Bay Packers", league: "NFL", api_id: "GB", api_used: "sportsfeed" },
  { name: "Houston Texans", league: "NFL", api_id: "HOU", api_used: "sportsfeed" },
  { name: "Indianapolis Colts", league: "NFL", api_id: "IND", api_used: "sportsfeed" },
  { name: "Jacksonville Jaguars", league: "NFL", api_id: "JAX", api_used: "sportsfeed" },
  { name: "Kansas City", league: "NFL", api_id: "KC", api_used: "sportsfeed" },
  { name: "Los Angeles Chargers", league: "NFL", api_id: "LAC", api_used: "sportsfeed" },
  { name: "Los Angeles Rams", league: "NFL", api_id: "LA", api_used: "sportsfeed" },
  { name: "Las Vegas Raiders", league: "NFL", api_id: "LV", api_used: "sportsfeed" },
  { name: "Miami Dolphins", league: "NFL", api_id: "MIA", api_used: "sportsfeed" },
  { name: "Minnesota Vikings", league: "NFL", api_id: "MIN", api_used: "sportsfeed" },
  { name: "New Enland Patriots", league: "NFL", api_id: "NE", api_used: "sportsfeed" },
  { name: "New Orleans Saints", league: "NFL", api_id: "NO", api_used: "sportsfeed" },
  { name: "New York Giants", league: "NFL", api_id: "NYG", api_used: "sportsfeed" },
  { name: "New York Jets", league: "NFL", api_id: "NYJ", api_used: "sportsfeed" },
  { name: "Philadelphia Eagles", league: "NFL", api_id: "PHI", api_used: "sportsfeed" },
  { name: "Pittsburgh Steelers", league: "NFL", api_id: "PIT", api_used: "sportsfeed" },
  { name: "San Francisco 49ers", league: "NFL", api_id: "SF", api_used: "sportsfeed" },
  { name: "Seattle Seahawks", league: "NFL", api_id: "SEA", api_used: "sportsfeed" },
  { name: "Tampa Bay Buccaneers", league: "NFL", api_id: "TB", api_used: "sportsfeed" },
  { name: "Tennessee Titans", league: "NFL", api_id: "TEN", api_used: "sportsfeed" },
  { name: "Washington Football Team", league: "NFL", api_id: "WAS", api_used: "sportsfeed" },

  ### NBA
  { name: "Dallas Mavericks", league: "NBA", api_id: "DAL", api_used: "sportsfeed" },
  { name: "Atlanta Hawks", league: "NBA", api_id: "ATL", api_used: "sportsfeed" },
  { name: "Brooklyn Nets", league: "NBA", api_id: "BRO", api_used: "sportsfeed" },
  { name: "Charlotte Hornets", league: "NBA", api_id: "CHA", api_used: "sportsfeed" },
  { name: "Chicago Bulls", league: "NBA", api_id: "CHI", api_used: "sportsfeed" },
  { name: "Cleveland Cavaliers", league: "NBA", api_id: "CLE", api_used: "sportsfeed" },
  { name: "Denver Nuggets", league: "NBA", api_id: "DEN", api_used: "sportsfeed" },
  { name: "Detroit Pistons", league: "NBA", api_id: "DET", api_used: "sportsfeed" },
  { name: "Golden State Warriors", league: "NBA", api_id: "GSW", api_used: "sportsfeed" },
  { name: "Houston Rockets", league: "NBA", api_id: "HOU", api_used: "sportsfeed" },
  { name: "Indiana Pacers", league: "NBA", api_id: "IND", api_used: "sportsfeed" },
  { name: "Los Angeles Clippers", league: "NBA", api_id: "LAC", api_used: "sportsfeed" },
  { name: "Los Angeles Lakers", league: "NBA", api_id: "LAL", api_used: "sportsfeed" },
  { name: "Memphis Grizzlies", league: "NBA", api_id: "LAL", api_used: "sportsfeed" },
  { name: "Miami Heat", league: "NBA", api_id: "MIA", api_used: "sportsfeed" },
  { name: "Milwaukee Bucks", league: "NBA", api_id: "MIL", api_used: "sportsfeed" },
  { name: "Minnesota Tinberwolves", league: "NBA", api_id: "MIN", api_used: "sportsfeed" },
  { name: "New Orleans Pelicans", league: "NBA", api_id: "NOP", api_used: "sportsfeed" },
  { name: "New York Knicks", league: "NBA", api_id: "NYK", api_used: "sportsfeed" },
  { name: "Oklahoma Thunder", league: "NBA", api_id: "OKL", api_used: "sportsfeed" },
  { name: "Philadelphia 76ers", league: "NBA", api_id: "PHI", api_used: "sportsfeed" },
  { name: "Phoenix Suns", league: "NBA", api_id: "PHX", api_used: "sportsfeed" },
  { name: "Portland Trailblazers", league: "NBA", api_id: "POR", api_used: "sportsfeed" },
  { name: "Sacramento Kings", league: "NBA", api_id: "SAC", api_used: "sportsfeed" },
  { name: "San Antonio Spurs", league: "NBA", api_id: "SAS", api_used: "sportsfeed" },
  { name: "Toronto Raptors", league: "NBA", api_id: "TOR", api_used: "sportsfeed" },
  { name: "Utah Jazz", league: "NBA", api_id: "UTA", api_used: "sportsfeed" },
  { name: "Washington Wizards", league: "NBA", api_id: "WAS", api_used: "sportsfeed" },

  ### NHL
  { name: "Ottawa Senators", league: "NHL", api_id: "OTT", api_used: "sportsfeed" },
  { name: "San Jose Sharks", league: "NHL", api_id: "SJS", api_used: "sportsfeed" },
  { name: "Anaheim Ducks", league: "NHL", api_id: "ANA", api_used: "sportsfeed" },
  { name: "Arizona Coyotes", league: "NHL", api_id: "ARI", api_used: "sportsfeed" },
  { name: "Boston Bruins", league: "NHL", api_id: "BOS", api_used: "sportsfeed" },
  { name: "Buffalo Sabers", league: "NHL", api_id: "BUF", api_used: "sportsfeed" },
  { name: "Calgary Flames", league: "NHL", api_id: "CGY", api_used: "sportsfeed" },
  { name: "Carolina Hurrincanes", league: "NHL", api_id: "CAR", api_used: "sportsfeed" },
  { name: "Chicago Blackhawks", league: "NHL", api_id: "CHI", api_used: "sportsfeed" },
  { name: "Colorado Avalanche", league: "NHL", api_id: "COL", api_used: "sportsfeed" },
  { name: "Columbus Blue Jackets", league: "NHL", api_id: "CBJ", api_used: "sportsfeed" },
  { name: "Dallas Stars", league: "NHL", api_id: "DAL", api_used: "sportsfeed" },
  { name: "Detroit Red Wings", league: "NHL", api_id: "DET", api_used: "sportsfeed" },
  { name: "Edmonton Oilers", league: "NHL", api_id: "EDM", api_used: "sportsfeed" },
  { name: "Florida Panthers", league: "NHL", api_id: "FLO", api_used: "sportsfeed" },
  { name: "Los Angeles Kings", league: "NHL", api_id: "LAK", api_used: "sportsfeed" },
  { name: "Minnesota Wild", league: "NHL", api_id: "MIN", api_used: "sportsfeed" },
  { name: "Montreal Canadiens", league: "NHL", api_id: "MTL", api_used: "sportsfeed" },
  { name: "Nashville Predators", league: "NHL", api_id: "NSH", api_used: "sportsfeed" },
  { name: "New Jersey Devils", league: "NHL", api_id: "NJD", api_used: "sportsfeed" },
  { name: "New York Islanders", league: "NHL", api_id: "NYI", api_used: "sportsfeed" },
  { name: "New York Rangers", league: "NHL", api_id: "NYR", api_used: "sportsfeed" },
  { name: "Phildelphia Flyers", league: "NHL", api_id: "PHI", api_used: "sportsfeed" },
  { name: "Pittsburgh Penguins", league: "NHL", api_id: "PIT", api_used: "sportsfeed" },
  { name: "St. Louis Blues", league: "NHL", api_id: "STL", api_used: "sportsfeed" },
  { name: "Tampa Bay Lightning", league: "NHL", api_id: "TBL", api_used: "sportsfeed" },
  { name: "Toronto Maple Leafs", league: "NHL", api_id: "TOR", api_used: "sportsfeed" },
  { name: "Vancouver Canucks", league: "NHL", api_id: "VAN", api_used: "sportsfeed" },
  { name: "Vegas Golden Knights", league: "NHL", api_id: "VGK", api_used: "sportsfeed" },
  { name: "Washingon Capitals", league: "NHL", api_id: "WSH", api_used: "sportsfeed" },
  { name: "Winnipeg Jets", league: "NHL", api_id: "WPJ", api_used: "sportsfeed" },

  ### MLB
  { name: "New York Yankees", league: "MLB", api_id: "OAK", api_used: "sportsfeed" },
  { name: "Arizona Diamondbacks", league: "MLB", api_id: "ARI", api_used: "sportsfeed" },
  { name: "Atlanta Braves", league: "MLB", api_id: "ATL", api_used: "sportsfeed" },
  { name: "Baltimore Orioles", league: "MLB", api_id: "BAL", api_used: "sportsfeed" },
  { name: "Boston Red Sox", league: "MLB", api_id: "BOS", api_used: "sportsfeed" },
  { name: "Chicago White Sox", league: "MLB", api_id: "CWS", api_used: "sportsfeed" },
  { name: "Chicago Cubs", league: "MLB", api_id: "CHC", api_used: "sportsfeed" },
  { name: "Cincinnati Reds", league: "MLB", api_id: "CIN", api_used: "sportsfeed" },
  { name: "Colorado Rockies", league: "MLB", api_id: "COL", api_used: "sportsfeed" },
  { name: "Detroit Tigers", league: "MLB", api_id: "DET", api_used: "sportsfeed" },
  { name: "Houston Astros", league: "MLB", api_id: "HOU", api_used: "sportsfeed" },
  { name: "Kansas City Royals", league: "MLB", api_id: "KC", api_used: "sportsfeed" },
  { name: "Los Angeles Angels", league: "MLB", api_id: "LAA", api_used: "sportsfeed" },
  { name: "Los Angeles Dodgers", league: "MLB", api_id: "LAD", api_used: "sportsfeed" },
  { name: "Miami Marlins", league: "MLB", api_id: "MIA", api_used: "sportsfeed" },
  { name: "Milwaukee Brewers", league: "MLB", api_id: "MIL", api_used: "sportsfeed" },
  { name: "Minnesota Twins", league: "MLB", api_id: "MIN", api_used: "sportsfeed" },
  { name: "Minnesota Twins", league: "MLB", api_id: "MIN", api_used: "sportsfeed" },
  { name: "New York Mets", league: "MLB", api_id: "NYM", api_used: "sportsfeed" },
  { name: "Oakland Athletics", league: "MLB", api_id: "OAK", api_used: "sportsfeed" },
  { name: "Philadelphia Phillies", league: "MLB", api_id: "PHI", api_used: "sportsfeed" },
  { name: "Pittsburgh Pirates", league: "MLB", api_id: "PHI", api_used: "sportsfeed" },
  { name: "San Diego Padres", league: "MLB", api_id: "SD", api_used: "sportsfeed" },
  { name: "San Franciso Giants", league: "MLB", api_id: "SF", api_used: "sportsfeed" },
  { name: "Seattle Mariners", league: "MLB", api_id: "SEA", api_used: "sportsfeed" },
  { name: "St Louis Cardinals", league: "MLB", api_id: "STL", api_used: "sportsfeed" },
  { name: "Tampa Bay Rays", league: "MLB", api_id: "TB", api_used: "sportsfeed" },
  { name: "Texas Rangers", league: "MLB", api_id: "TEX", api_used: "sportsfeed" },
  { name: "Toronto Blue Jays", league: "MLB", api_id: "TOR", api_used: "sportsfeed" },
  { name: "Washington Nationals", league: "MLB", api_id: "WAS", api_used: "sportsfeed" },

])

# user_team = UserTeam.create!([
#   { user_id: 1, team_id: 1 },
#   { user_id: 1, team_id: 3 },
#   { user_id: 2, team_id: 2 },
#   { user_id: 2, team_id: 1 },
#   { user_id: 3, team_id: 3 },
#   { user_id: 3, team_id: 2 },
# ])
